name: Deployment

on:
  push:
    tags:
      - v*.*.*

jobs:
  # Deploy release
  deploy:
    runs-on: ubuntu-18.04
    container: johnmcfarlane/cnl_ci:gcc-10
    steps:
    - uses: actions/checkout@v2

    - name: Generate documentation
      shell: bash
      run: $GITHUB_WORKSPACE/doc/generate.sh

    - name: Deploy
      shell: bash
      run: CNL_VERSION=$GITHUB_REF $GITHUB_WORKSPACE/.github/deploy.sh
