---
name: pr

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  # Build and test latest on Linux using only CMake
  cmake:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: clang
            stdlib-flag: "-stdlib=libc++"
            toolchain: clang-libc++.cmake
            container: johnmcfarlane/cnl_ci:clang-head-libcpp
          - compiler: gcc
            stdlib-flag: "-fsanitize=address,undefined"
            toolchain: gcc.cmake
            container: johnmcfarlane/cnl_ci:gcc-12
        build_type: ["Release", "Debug"]
        cxx-extensions: ["ON", "OFF"]
        exceptions: ["ON", "OFF"]

    container: ${{matrix.container}}
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Restore Compiler Cache
        uses: hendrikmuhs/ccache-action@v1
        env:
          CACHE_SLUG: cmake-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.cxx-extensions }}-${{ matrix.exceptions }}
        with:
          key: ${{ env.CACHE_SLUG }}-${{ hashFiles('test/toolchain/**') }}

      - name: Cache Report
        run: |
          ccache -s

      - name: Build and Install GTest
        env:
          CXXFLAGS: ${{matrix.stdlib-flag}}
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          git checkout 8d51dc50eb7e7698427fed81b85edad0e032112e
          cmake \
            -DCMAKE_CXX_COMPILER_LAUNCHER:STRING=ccache \
            -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$GITHUB_WORKSPACE/test/toolchain/${{matrix.toolchain}} \
            .
          cmake --build . --target install

      - name: Configure CNL
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DCMAKE_CXX_COMPILER_LAUNCHER:STRING=ccache \
            -DCMAKE_CXX_EXTENSIONS=${{matrix.cxx-extensions}} \
            -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$GITHUB_WORKSPACE/test/toolchain/${{matrix.toolchain}} \
            -DCNL_EXCEPTIONS=${{matrix.exceptions}} \
            -DCNL_SANITIZE=ON \
            $GITHUB_WORKSPACE

      - name: Build CNL
        run: cmake --build $GITHUB_WORKSPACE --target test-all

      - name: Test CNL
        run: ctest --output-on-failure

  # Install on mature Linux distro using only CMake
  install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure CNL
        run: cmake $GITHUB_WORKSPACE

      - name: Install CNL
        run: sudo cmake --build $GITHUB_WORKSPACE --target install

  # Test shell scripts
  shellcheck:
    runs-on: ubuntu-20.04
    container: johnmcfarlane/cnl_ci:base-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run shellcheck
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          $GITHUB_WORKSPACE/test/scripts/shellcheck

  # Test markdown
  markdownlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run markdownlint
        shell: bash
        run: |
          sudo snap install mdl
          $GITHUB_WORKSPACE/test/scripts/markdownlint

  # Test YAML
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run yamllint
        shell: bash
        run: |
          sudo apt install yamllint
          $GITHUB_WORKSPACE/test/scripts/yamllint
...
